# Render deployment configuration
services:
  # Backend API service
  - type: web
    name: suvvidha-api
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: JWT_SECRET
        sync: false
      - key: MONGO_URI
        sync: false
    autoDeploy: true

  # Frontend static site
  - type: web
    name: suvvidha-client
    env: static
    buildCommand: cd client && npm install && npm run build
    staticPublishPath: ./client/build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: NODE_ENV
        value: production
    autoDeploy: true