services:
  - type: web
    name: suvvidha
    env: node
    buildCommand: npm install && npm run install-client && cd client && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false