services:
  - type: web
    name: suvvidha
    env: node
    buildCommand: |
      export NODE_OPTIONS="--max_old_space_size=512"
      npm ci --production=false
      npm run install-client --production=false
      cd client && npm run build
      cd .. && npm prune --production
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: NODE_OPTIONS
        value: --max_old_space_size=512